"""empty message

Revision ID: 55b7377e0a59
Revises: f3f1b9af0118
Create Date: 2023-09-28 17:26:12.349031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '55b7377e0a59'
down_revision: Union[str, None] = 'f3f1b9af0118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'message_count')
    # ### end Alembic commands ###
